/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// This is the comprehensive list of streets for Auburn Lake Trails.
export const ALT_STREETS = [
  "Ahwahnee Court",
  "American River Trail",
  "Angel Camp Court",
  "Bald Eagle Court",
  "Balloon Ridge Court",
  "Balloon Ridge Trail",
  "Beaver Creek Road",
  "Big Chief Trail",
  "Big Clipper Court",
  "Big Nugget Court",
  "Big Nugget Trail",
  "Big Strike Trail",
  "Black Rock Lane",
  "Blue Bell Court",
  "Blue Mountain Court",
  "Blue Tent Court",
  "Bobcat Lane",
  "Bogus Point Court",
  "Bottle Hill Court",
  "Brinks Lane",
  "Brown Bear Court",
  "Brown Bear Trail",
  "Brushy Canyon Trail",
  "Bud's Alley",
  "Burnt Flat Trail",
  "Calle Fresca Way",
  "Cascade Trail",
  "Cattail Court",
  "Cauchoo Court",
  "Cherokee Court",
  "Chicken Hawk Court",
  "Chimney Flat Court",
  "Circle Drive",
  "Claim Stake Court",
  "Clipper Court",
  "Cool Way",
  "Coon Court",
  "Coon Creek Road",
  "Coyote Creek Court",
  "Cramer Court",
  "Cramer Road",
  "Deadwood Court",
  "Deer Ravine Court",
  "Deer Ravine Trail",
  "Deer Run Court",
  "Digger Tree Court",
  "Double O Mine Court",
  "Double O Mine Trail",
  "Dutch Camp Court",
  "Fork House Court",
  "Gamblers Court",
  "Genevieve",
  "Gravel Gulch Court",
  "Greenhorn Court",
  "Greenhorn Trail",
  "Grouse Ridge Court",
  "Grouse Ridge Trail",
  "Hidden Gold Court",
  "Hidden Gold Trail",
  "Hotchkiss Court",
  "Indian Trail",
  "Kit Fox Court",
  "Lake City Court",
  "Last Chance Court",
  "Liberty Hill Court",
  "Ligaya Lane",
  "Lois Lane",
  "Lou Allen Lane",
  "Lovers Leap Court",
  "Lyons Creek Court",
  "Magic Morgan Trail",
  "Mariposa Court",
  "Maydress Court",
  "Middle Mountain Court",
  "Mirinda Lane",
  "Muir Court",
  "Onion Flat Court",
  "Otter Court",
  "Otter Place",
  "Otter Trail",
  "Out West Court",
  "Paymaster Court",
  "Paymaster Trail",
  "Penobscot Road",
  "Pepper Boy Court",
  "Pickering Court",
  "Pilgrim Court",
  "Pointed Rocks Trail",
  "Rawhide Court",
  "Rita Court",
  "Rockbound Court",
  "Roses Bar Court",
  "Roses Bar Trail",
  "Rycarba Lane",
  "Sage Hill Court",
  "Sawtooth Court",
  "Scotty Dog Lane",
  "Secret Canyon Trail",
  "Secret Diggin Court",
  "Secret Lake Court",
  "Secret Lake Trail",
  "Secret Ravine Trail",
  "Shirt Tail Court",
  "Shirt Tail Trail",
  "Sore Finger Court",
  "Squires Canyon Court",
  "Stardome Lane",
  "Stoney Bar Court",
  "Stoney Hill Court",
  "Strap Miner Court",
  "Strap Miner Trail",
  "Swamp Angel Court",
  "Sweetwater Court",
  "Sweetwater Trail",
  "Talking Mountain Trail",
  "Tegra Court",
  "Tegra Road",
  "Terry Kirrley Road",
  "Trading Post Court",
  "Trillium Lane",
  "Triple Seven Road",
  "Upper Black Rock Road",
  "Urban Retreat Lane",
  "Wagon Wheel Court",
  "Westville Trail",
  "Wild Cat Court",
  "Wild West Trail",
  "Wildcat Flat Trail",
  "Willow Creek Court",
  "Willow Creek Trail",
  "Wind Mill Court",
  "Windy Court",
  "Yankee Jim Court"
];

export const isValidStreet = (street: string) => {
  return ALT_STREETS.some(s => s.toLowerCase() === street.toLowerCase());
};
